package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

# LLVM lit configurations for lit test in OSS environment.
filegroup(
    name = "litcfgs",
    srcs = glob(["lit*py"]),
)
